on:
  pull_request_review:
    types: [submitted]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: labeler-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          target-approved-count: 1
          label-to-be-added: 'Accepted'
          label-to-be-removed: 'In Review'